# -*- coding: utf-8 -*-
"""makemore1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4Dv6dEeVWzPX7M0A-r8tzTOzR9oZNEJ

**bigrad char language level**
"""

# word = open(r'/content/Arabnames (1).txt', 'r').read().splitlines()
# word = [w.lower().replace('.', '').replace(' ', '') for w in word]
word = open(r'/content/names.txt', 'r').read().splitlines()
train=word[:int(0.8*len(word))]
dev=word[int(0.8*len(word)):int(0.9*len(word))]
test=word[int(0.9*len(word)):]
word[:3]

# b={} #dictionary map  each distincit sequence of two char with its number in the dataset
# for w in word[1:]:
#    chs=['<S>']+list(w)+['<E>'] #to add the sequence of starting and ending to for example to add the end and start to the frequency charchters
#    for ch1,ch2 in zip(chs,chs[1:]):
#        bigram=(ch1,ch2)
#        b[bigram]=b.get(bigram,0)+1 # it will search in the dic about tuple(ch1,ch2) if it is not found assign in it to 0 and then add 1 if
#        #found it ,it will return the number frequency of it and add one to it

# sorted(b.items(),key=lambda kv:-kv[1]) #it is pass the tuple in the b.item() to kv and return kv[1](value),then sorted based on it

import torch

"""**unique chars in dataset**"""

chars=sorted(list(set(''.join(word)))) #define all unique chars in dataset
stoi = {s:i+1 for i,s in enumerate(chars)} #map it to a number
stoi['.'] = 0 #put the begin and the end of the word as char and we do it like this
#not like this </s>,</e> to prevent wasting memory in cases of char,s and e,char
itos={i:s for s,i in stoi.items()} #map num to char

stoi

"""**probability distribution table using counting**"""

a=torch.zeros((27,27),dtype=torch.int32)
# a.dtype

for w in word:
   chs=['.'] +list(w)+ ['.'] #to add the sequence of starting and ending to for example to add the end and start to the frequency charchters
   for ch1,ch2 in zip(chs,chs[1:]):
       ix1=stoi[ch1]
       ix2=stoi[ch2]
       a[ix1,ix2]+=1

"""tranform frequency to probablity"""

P=(a+1).float()
P/=P.sum(1,keepdim=True) #sums horizantly and keep the diemnsion
#the dim will be (27,1) and then this column vector will be copied 27 times
#as result of that it will normalize each row
# P

"""**prediction words**"""

g=torch.Generator().manual_seed(2147483647)
for i in range(5):
  ix=0
  out=[]
  while(True):
    p=P[ix]
    # p=a[ix].float() #to do divide correctly
    # p=p/p.sum() #probability distribution of each row
    # p=torch.ones(27)/27.0 #that is the non trained model
    ix=torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
    #choose sample from indexes in the input row according to it propability distribution
    out.append(itos[ix])
    if ix==0:
      break
  print(''.join(out))

"""**loss funciton**

"""

logliklihood=0
n=0
# for w in ['andrejq']:
for w in word:
   chs=['.']+list(w)+['.'] #to add the sequence of starting and ending to for example to add the end and start to the frequency charchters
   for ch1,ch2 in zip(chs,chs[1:]):
       xi1=stoi[ch1]
       xi2=stoi[ch2]
       prob=P[xi1,xi2]
       logprob=torch.log(prob)
       logliklihood+=logprob
       n+=1
      #  print(f'{ch1},{ch2} :{prob:.4f},{logprob:.4f}')
print(f'{logliklihood=}')
nll=-logliklihood
print(f'{nll=}')
print(f'{nll/n}')

"""**visualize pd**"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
plt.figure(figsize=(16,16))
plt.imshow(a,cmap='Blues')
for i in range(27):
  for j in range(27):
    chstr=itos[i]+itos[j]
    plt.text(j,i,chstr,ha='center',va='bottom',color='gray')
    plt.text(j,i,a[i,j].item(),ha='center',va='top',color='gray')
plt.axis('off');

# g=torch.Generator().manual_seed(2147483647)
# p=torch.rand(3,generator=g) #choose 3 random nums
# p/=p.sum()#calculate it distribution
# p

#if we make keepdim=False and just depending on
#broadcasting it won't work because it will be
#(1,27) and we copied 27 times then divide by it
#it will normalize the columns not the rows

"""**bigram using nn**

char-->get :index-->one_hot_encoding-->get into neural network -->exp the row res(interpert 27 out of the neural network as probabilty of next char to come next )-->calc prob of it
"""

xs=[]
ys=[]
for w in word[:3]:
   chs=['.']+list(w)+['.'] #to add the sequence of starting and ending to for example to add the end and start to the frequency charchters
   for ch1,ch2 in zip(chs,chs[1:]):
       xi=stoi[ch1]
       yi=stoi[ch2]
      #  print(ch1,ch2)
       xs.append(xi)
       ys.append(yi)
xs=torch.tensor(xs)
ys=torch.tensor(ys)
print(xs)
print(ys)

"""encoding inputs"""

import torch.nn.functional as f
xenc=f.one_hot(xs,num_classes=27).float()
plt.imshow(xenc)
xenc

"""initialize neural net"""

g=torch.Generator().manual_seed(2147483647)
#randomly initialize 27 neurons (weights) ,each neuron has 27 input
w=torch.randn((27,27),generator=g) #create random samples according to normal distribution
print((xenc @ w)[3,13]) #input number 3 in neuron 13 (xenc[3]*w[:,13]).sum()
print((xenc[3]*w[:,13]).sum())

"""forward pass

next chars prob based on nn
"""

#plugin each input example xs to a neural net
#multiply each row of input (encoding char 5*27) to all columns(27*27) of w
#and each char out one row of probability ,all rows produce (5*27)
logit=xenc @ w #log counts
#because of matrix multiplication properites the output will be the
#i index of the char in the w ex. if we input a-->1 it will out the w[1]in tne w
#we interpert each row to look like counts so we use exp because it
#has the behaviour of counts (it's positive only) it is turn negative to
#<0<n<1 and 1<p

#softmax function (because it is classification problem) activiation funciton
counts=logit.exp()
probs=counts/counts.sum(1,keepdim=True)
probs

nlls=torch.zeros(5)
for i in range(5):
  x=xs[i].item()
  y=ys[i].item()
  print(f"-----------------------------------")
  print(f"bigram example{i+1},itmes:{itos[x]},{itos[y]},index:{x},{y}")
  print(f"input to nn:{x} ")
  print(f"out probs from nn:{probs[i]}")
  p=probs[i,y]
  print(f"right next index char:{y},it is prob {p.item()}")
  logp=torch.log(p)
  print(f"log prob: {logp}")
  nll=-logp
  print(f"nll: {nll}")
  nlls[i]=nll
print("================")
print(f"loss: {nlls.mean().item()}")

"""**optimization**"""

import torch

#create a dataset
xs=[]
ys=[]
for w in train:
   chs=['.']+list(w)+['.']
   for ch1,ch2 in zip(chs,chs[1:]):
       xi=stoi[ch1]
       yi=stoi[ch2]
       xs.append(xi)
       ys.append(yi)
xs=torch.tensor(xs)
ys=torch.tensor(ys)
nums=xs.nelement()
print(f"number of element: {nums}")
#initialize nn
g=torch.Generator().manual_seed(2147483647)
w=torch.randn((27,27),generator=g,requires_grad=True)

import torch.nn.functional as f
for k in range(100):

    #forward pass
    xenc=f.one_hot(xs,num_classes=27).float()
    logit=xenc @ w
    counts=logit.exp()
    probs=counts/counts.sum(1,keepdim=True)

    #cress entropy loss funciton +regularization
    loss=-probs[torch.arange(nums),ys].log().mean()+0.01*(w**2).mean()
    print(loss.item())

    #zero grad
    w.grad=None
    #backward pass
    loss.backward()

    #update
    w.data += -50 * w.grad

"""evaluate test and dev data"""

loss=[]
for wt in test:
   chs=['.']+list(wt)+['.']
   for ch1,ch2 in zip(chs,chs[1:]):
       xi=stoi[ch1]
       yi=stoi[ch2]
       xenc=f.one_hot(torch.tensor(xi),num_classes=27).float()
       logit=xenc @ w.data
       counts=logit.exp()
       probs=counts/counts.sum()
       loss.append(-probs[yi].log())
loss=torch.tensor(loss)
print(loss.mean())

loss=[]
for wt in dev:
   chs=['.']+list(wt)+['.']
   for ch1,ch2 in zip(chs,chs[1:]):
       xi=stoi[ch1]
       yi=stoi[ch2]
       xenc=f.one_hot(torch.tensor(xi),num_classes=27).float()
       logit=xenc @ w.data
       counts=logit.exp()
       probs=counts/counts.sum()
       loss.append(-probs[yi].log())
loss=torch.tensor(loss)
print(loss.mean())

counts.shape

"""make words"""

g=torch.Generator().manual_seed(2147483647)
for i in range(20):
  ix=0
  out=[]
  while(True):
    # logit=w[ix]
    xenc=f.one_hot(torch.tensor([xi]),num_classes=27).float()
    logit=xenc @ w
    counts=logit.exp()
    p=counts/counts.sum(1,keepdim=True)
    ix=torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
    out.append(itos[ix])
    if ix==0:
      break
  print(''.join(out))

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
plt.figure(figsize=(16,16))
plt.imshow(w.data,cmap='Blues')
for i in range(27):
  for j in range(27):
    chstr=itos[i]+itos[j]
    plt.text(j,i,chstr,ha='center',va='bottom',color='gray')
    plt.text(j,i,w[i,j].data,ha='center',va='top',color='gray')
plt.axis('off');

from graphviz import Digraph
import torch

def draw_dot_detailed(root):
    dot = Digraph(format='svg', graph_attr={'rankdir': 'LR'})
    nodes, edges = set(), set()

    def add_nodes(fn):
        if fn is not None and fn not in nodes:
            nodes.add(fn)
            uid = str(id(fn))

            # تحديد اسم العملية وشكلها
            op_name = type(fn).__name__.replace('Backward', '')
            dot.node(name=uid, label="{ op: %s }" % op_name, shape='ellipse', color='red')

            # البحث عن المدخلات (الأبناء) في خريطة Autograd
            if hasattr(fn, 'next_functions'):
                for i, (child, _) in enumerate(fn.next_functions):
                    if child is not None:
                        # إذا كان الابن هو عملية أخرى
                        child_uid = str(id(child))
                        dot.edge(child_uid, uid, label=f"input_{i}")
                        add_nodes(child)
                    else:
                        # هنا بايتورش يخفي الـ Leaf Tensors (الأوزان الأصيلة)
                        # سنرسم مربعاً وهمياً لتمثيل المدخل المفقود في الرسم
                        leaf_uid = uid + str(i)
                        dot.node(name=leaf_uid, label="Leaf/Weight", shape='box', style='dashed')
                        dot.edge(leaf_uid, uid)

    # نبدأ من الـ grad_fn الخاص بالـ Loss
    if hasattr(root, 'grad_fn') and root.grad_fn is not None:
        add_nodes(root.grad_fn)
    else:
        return "Error: This tensor does not have a grad_fn. Make sure it's a result of an operation!"

    return dot

draw_dot(loss)