# -*- coding: utf-8 -*-
"""Copy of mlp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmzWhSsEOWgCDlWVgMhUn55qhqO_Fm0f
"""

# Commented out IPython magic to ensure Python compatibility.
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
from tqdm import notebook
import pandas as pd
import seaborn as sns
# %matplotlib inline

words = open('names.txt', 'r').read().splitlines()
words[:8]

# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

# build the dataset
def build_dataset(words,block_size):
  X, Y = [], []
  for w in words:

    #print(w)
    context = [0] * block_size
    for ch in w + '.':
      ix = stoi[ch]
      X.append(context)
      Y.append(ix)
      #print(''.join(itos[i] for i in context), '--->', itos[ix])
      context = context[1:] + [ix] # crop and append

  X = torch.tensor(X)
  Y = torch.tensor(Y)
  print(X.shape, Y.shape)
  return X, Y

import random
random.seed(42)
random.shuffle(words)
n1 = int(0.8*len(words))
n2 = int(0.9*len(words))
block_size=3
Xtr, Ytr = build_dataset(words[:n1],block_size)
Xdev, Ydev = build_dataset(words[n1:n2],block_size)
Xte, Yte = build_dataset(words[n2:],block_size)

# g = torch.Generator().manual_seed(2147483647) # for reproducibility
# C = torch.randn((27, 2), generator=g)
# W1=torch.randn((6,100), generator=g)
# b1=torch.randn((100), generator=g)
# W2=torch.randn((100,27), generator=g)
# b2=torch.randn((27), generator=g)
# parameters=[C,W1,b1,W2,b2]

g = torch.Generator().manual_seed(2147483647) # for reproducibility
C = torch.randn((27, 10), generator=g)
W1=torch.randn((30,200), generator=g)
b1=torch.randn((200), generator=g)
W2=torch.randn((200,27), generator=g)
b2=torch.randn((27), generator=g)
parameters=[C,W1,b1,W2,b2]

for p in parameters:
  p.requires_grad=True

#find the best lr hyperparameter
lre=torch.linspace(-3,0,1000)
lrs=10**lre

lri=[]
lossi=[]
stepsi=[]

max_steps=20000
batch_size=32
for i in range(max_steps):
  #mini batches
  xi=torch.randint(0,Xtr.shape[0],(batch_size,)) #index for char
  #forward pass
  emb=C[Xtr[xi]] #(32,3,2)
  h= torch.tanh(emb.view(-1,emb.shape[-2]*emb.shape[-1])@ W1+b1) #(32,200)
  logits= h @ W2 + b2
  loss=F.cross_entropy(logits, Ytr[xi]) #(32,27)
  # print(loss.item())

  #backward pass
  for p in parameters:
    p.grad=None
  loss.backward()

  # lr=lrs[i] #for finetune hyper parameter
  lr=0.1 if i<10000 else 0.01
  #update
  for p in parameters:
    p.data+=-lr*p.grad

  # track stats
  # lri.append(lrs[i])
  # lri.append(lre[i])
  stepsi.append(i)
  lossi.append(loss.item())
print(loss.item())

# plt.plot(lri,lossi)
plt.plot(stepsi,lossi)

# training loss
emb=C[Xtr]
h= torch.tanh(emb.view(-1,30)@ W1+b1)
logits= h @ W2 + b2
loss=F.cross_entropy(logits, Ytr)
print(loss.item())

# validation loss
emb=C[Xdev]
h= torch.tanh(emb.view(-1,30)@ W1+b1)
logits= h @ W2 + b2
loss=F.cross_entropy(logits, Ydev)
print(loss.item())

# test loss
emb=C[Xdev]
h= torch.tanh(emb.view(-1,30)@ W1+b1)
logits= h @ W2 + b2
loss=F.cross_entropy(logits, Ydev)
print(loss.item())

plt.figure(figsize=(8,8))
plt.scatter(C[:,0].data, C[:,1].data, s=200)
for i in range (C.shape[0]):
  plt.text(C[i,0].item(), C[i,1].item(), itos[i], ha="center", va="center", color='white')
plt.grid('minor')

# sample from the model
g = torch.Generator().manual_seed(2147483647 + 10)

for _ in range(20):

    out = []
    context = [0] * block_size # initialize with all ...
    while True:
      emb = C[torch.tensor([context])] # (1,block_size,d)
      h = torch.tanh(emb.view(1, -1) @ W1 + b1)
      logits = h @ W2 + b2
      probs = F.softmax(logits, dim=1)
      ix = torch.multinomial(probs, num_samples=1, generator=g).item()
      context = context[1:] + [ix]
      out.append(ix)
      if ix == 0:
        break

    print(''.join(itos[i] for i in out))

class MLP:
    def __init__(
        self,
        emb_dim1,
        emb_dim2,
        l1_out_features,
        l2_out_features,
        num_epochs,
        learning_rate,
        block_size=3,
        minibatch_size=32,
        loss_update_steps=1000,
        display_train_loss=True,
        seed=2147483647
        ):
          """Constructor for MLP class."""
          # Creating class attributes
          self.emb_dim_1 = emb_dim1
          self.emb_dim_2 = emb_dim2
          self.l1_out_features = l1_out_features
          self.l2_out_features = l2_out_features
          self.num_epochs = num_epochs
          self.learning_rate = learning_rate
          self.block_size = block_size
          self.minibatch_size = minibatch_size
          self.loss_update_steps = loss_update_steps
          self.display_train_loss = display_train_loss
          self.seed = seed

          g = torch.Generator().manual_seed(self.seed) # for reproducibility
          self.C = torch.randn((self.emb_dim_1,self.emb_dim_2), generator=g)
          self.W1=torch.randn((self.block_size*self.emb_dim_2,self.l1_out_features), generator=g)
          self.b1=torch.randn((self.l1_out_features), generator=g)
          self.W2=torch.randn((self.l1_out_features,self.l2_out_features), generator=g)
          self.b2=torch.randn((self.l2_out_features), generator=g)
          self.parameters = [self.C, self.W1, self.b1, self.W2, self.b2]
          self.num_params = sum(p.nelement() for p in self.parameters)

          for p in parameters:
            p.requires_grad=True

    def call(self,x,y):
      #forward pass
      emb=self.C[x]
      h= torch.tanh(emb.view(-1,emb.shape[-1]*emb.shape[-2])@ self.W1+self.b1)
      logits= h @ self.W2 + self.b2
      loss=F.cross_entropy(logits, y)
      return loss

    def fit(self,x,y):
      loss_per_epoch = {}
      epoch_counter = notebook.tqdm(range(self.num_epochs))
      for k in epoch_counter:
          #mini batches
          xi=torch.randint(0,x.shape[0],(self.minibatch_size,))
          loss=self(x[xi],y[xi])
          if self.display_train_loss and ((k % self.loss_update_steps == 0) or (k == self.num_epochs-1)):
              epoch_counter.set_postfix({"train_loss": loss.item()})
          # Adding a loss computed to the history
          loss_per_epoch[f"epoch_{k+1}"] = loss.item()
          #backward pass
          for p in parameters:
            p.grad=None
          loss.backward()
          #update
          for p in parameters:
            p.data-=self.learning_rate*p.grad
      self.history = loss_per_epoch
    @property
    def loss_function(self,x,y):
      if not hasattr(self,"history"):
        rte_msg = (
          "MLP class does not yet have data about the loss. "
          "Run 'fit' method first."
          )
        raise RuntimeError(rte_msg)
      loss_info=pd.Series(self.history.values())
      loss_info.plot()
      plt.xlabel("Epochs")
      plt.ylabel("NLL loss")
      plt.title("Loss evolution")
      plt.tight_layout()
      plt.show()

    def tune_learning_rate(self,x,y,lower_exp=-3,upper_exp=0):
      lre=torch.linspace(lower_exp,upper_exp,self.num_epochs)
      lrs=10**lre
      losses=[]
      learning_rates_exponents=[]
      epoch_counter = notebook.tqdm(range(self.num_epochs))

      for k in epoch_counter:
          #mini batches
          xi=torch.randint(0,x.shape[0],(batch_size,))
          loss=self(x[ix],y[ix])
          #backward pass
          for p in parameters:
            p.grad=None
          loss.backward()

          lr=lrs[k] #for finetune hyper parameter
          #update
          for p in parameters:
            p.data+=-lr*p.grad

            # track stats
            learning_rates_exponents.append(lrs[i])
            losses.append(loss.item())
      plt.plt(learning_rates_exponents,losses)
      plt.xlabel("LR exponent")
      plt.ylabel("NLL loss")
      plt.title("Tuning learning_rate")
      plt.tight_layout()
      plt.show()
    def generate_sampel(self,num_examples,itos):
     # sample from the model
     g = torch.Generator().manual_seed(self.seed)
     generated_names=[]
     for _ in range(num_examples):
         out = []
         context = [0] * block_size # initialize with all ...
         while True:
           emb = C[torch.tensor([context])] # (1,block_size,d)
           h = torch.tanh(emb.view(1, -1) @ W1 + b1)
           logits = h @ W2 + b2
           probs = F.softmax(logits, dim=1)
           ix = torch.multinomial(probs, num_samples=1, generator=g).item()
           context = context[1:] + [ix]
           out.append(ix)
           if ix == 0:
             break
         generated_names.append(''.join(itos[i] for i in out)[:-1])
         return generated_names



@torch.nograd() #this tells pytorch to don't keep bookkeeping of computation because i don't do
#any backtracking so it saving memory
def split_loss(split):
  x,y={
      'train':(Xtr, Ytr),
       'test':(Xte, Yte),
       'dev':(Xdev, Ydev )
      }[split]
split_loss('train')
split_loss('dev')

# torch.cat([emb[:,0,1],emb[:,0,1],emb[:,0,1]],1).shape
# torch.unbind(emb,1)
# emb.view(32,6)==torch.cat([emb[:,0,1],emb[:,0,1],emb[:,0,1]],1)

# counts=ligits.exp()
# prob=counts/counts.sum(1,keepdim=True)
# loss=-probs[torch.arrang(32),Y].log().mean()

#bigger sample size less oclliate

