# -*- coding: utf-8 -*-
"""mlp_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qU_zUMomDoN-C_q_1CcErtlrr-nuyPj0
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
from tqdm import notebook
import pandas as pd
import seaborn as sns
# %matplotlib inline

words = open('/content/drive/MyDrive/names.txt', 'r').read().splitlines()

# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

# build the dataset
def build_dataset(words,block_size):
  X, Y = [], []
  for w in words:

    #print(w)
    context = [0] * block_size
    for ch in w + '.':
      ix = stoi[ch]
      X.append(context)
      Y.append(ix)
      #print(''.join(itos[i] for i in context), '--->', itos[ix])
      context = context[1:] + [ix] # crop and append

  X = torch.tensor(X)
  Y = torch.tensor(Y)
  print(X.shape, Y.shape)
  return X, Y

import random
random.seed(42)
random.shuffle(words)
n1 = int(0.8*len(words))
n2 = int(0.9*len(words))
block_size=3
Xtr, Ytr = build_dataset(words[:n1],block_size)
Xdev, Ydev = build_dataset(words[n1:n2],block_size)
Xte, Yte = build_dataset(words[n2:],block_size)

class MLP:
    def __init__(
        self,
        emb_dim1,
        emb_dim2,
        l1_out_features,
        l2_out_features,
        num_epochs,
        learning_rate,
        block_size=3,
        minibatch_size=32,
        loss_update_steps=1000,
        display_train_loss=True,
        seed=2147483647
        ):
          """Constructor for MLP class."""
          # Creating class attributes
          self.emb_dim_1 = emb_dim1
          self.emb_dim_2 = emb_dim2
          self.l1_out_features = l1_out_features
          self.l2_out_features = l2_out_features
          self.num_epochs = num_epochs
          self.learning_rate = learning_rate
          self.block_size = block_size
          self.minibatch_size = minibatch_size
          self.loss_update_steps = loss_update_steps
          self.display_train_loss = display_train_loss
          self.seed = seed

          g = torch.Generator().manual_seed(self.seed) # for reproducibility
          self.C = torch.randn((self.emb_dim_1,self.emb_dim_2), generator=g)
          self.W1=torch.randn((self.block_size*self.emb_dim_2,self.l1_out_features), generator=g)
          self.b1=torch.randn((self.l1_out_features), generator=g)
          self.W2=torch.randn((self.l1_out_features,self.l2_out_features), generator=g)
          self.b2=torch.randn((self.l2_out_features), generator=g)
          self.parameters = [self.C, self.W1, self.b1, self.W2, self.b2]
          self.num_params = sum(p.nelement() for p in self.parameters)

          for p in self.parameters:
            p.requires_grad=True

    def __call__(self,x,y):
      #forward pass
      emb=self.C[x]
      h= torch.tanh(emb.view(-1,emb.shape[-1]*emb.shape[-2])@ self.W1+self.b1)
      self.h=h
      logits= h @ self.W2 + self.b2
      loss=F.cross_entropy(logits, y)
      return loss

    def fit(self,split):
      x,y={
      'train':(Xtr, Ytr),
       'test':(Xte, Yte),
       'dev':(Xdev, Ydev )
      }[split]
      loss_per_epoch = {}
      epoch_counter = notebook.tqdm(range(self.num_epochs))
      for k in epoch_counter:
          #mini batches
          xi=torch.randint(0,x.shape[0],(self.minibatch_size,))
          loss=self(x[xi],y[xi])
          if self.display_train_loss and ((k % self.loss_update_steps == 0) or (k == self.num_epochs-1)):
              epoch_counter.set_postfix({"train_loss": loss.item()})
          # Adding a loss computed to the history
          loss_per_epoch[f"epoch_{k+1}"] = loss.item()
          #backward pass
          for p in self.parameters:
            p.grad=None
          loss.backward()
          #update
          for p in self.parameters:
            p.data-=self.learning_rate*p.grad
      self.history = loss_per_epoch
    @property
    @torch.no_grad()
    def loss_function(self):
      if not hasattr(self,"history"):
        rte_msg = (
          "MLP class does not yet have data about the loss. "
          "Run 'fit' method first."
          )
        raise RuntimeError(rte_msg)
      loss_info=pd.Series(self.history.values())
      loss_info.plot()
      plt.xlabel("Epochs")
      plt.ylabel("NLL loss")
      plt.title("Loss evolution")
      plt.tight_layout()
      plt.show()

    def tune_learning_rate(self,split,lower_exp=-3,upper_exp=0):
      x,y={
       'train':(Xtr, Ytr),
       'test':(Xte, Yte),
       'dev':(Xdev, Ydev )
      }[split]
      lre=torch.linspace(lower_exp,upper_exp,self.num_epochs)
      lrs=10**lre
      losses=[]
      learning_rates_exponents=[]
      epoch_counter = notebook.tqdm(range(self.num_epochs))

      for k in epoch_counter:
          #mini batches
          ix=torch.randint(0,x.shape[0],(self.minibatch_size,))
          loss=self(x[ix],y[ix])
          #backward pass
          for p in self.parameters:
            p.grad=None
          loss.backward()

          lr=lrs[k] #for finetune hyper parameter
          #update
          for p in self.parameters:
            p.data+=-lr*p.grad

          # track stats
          learning_rates_exponents.append(lre[k])
          losses.append(loss.item())
      plt.plot(learning_rates_exponents,losses)
      plt.xlabel("LR exponent")
      plt.ylabel("NLL loss")
      plt.title("Tuning learning_rate")
      plt.tight_layout()
      plt.show()
    def generate_sampel(self,num_examples,itos):
      # sample from the model
      g = torch.Generator().manual_seed(self.seed)
      generated_names=[]
      for i in range(num_examples):
         out = []
         context = [0] * self.block_size # initialize with all ...
         while True:
           emb = self.C[torch.tensor([context])] # (1,block_size,d)
           h = torch.tanh(emb.view(1, -1) @ self.W1 + self.b1)
           logits = h @ self.W2 + self.b2
           probs = F.softmax(logits, dim=1)
           ix = torch.multinomial(probs, num_samples=1, generator=g).item()
           context = context[1:] + [ix]
           out.append(ix)
           if ix == 0:
             break
         generated_names.append(''.join(itos[i] for i in out)[:-1])
      return generated_names

mlp_model=MLP(
        emb_dim1=27,
        emb_dim2=10,
        l1_out_features=200,
        l2_out_features=27,
        num_epochs=1000,
        learning_rate=None)
mlp_model.tune_learning_rate('train')

mlp_model=MLP(
        emb_dim1=27,
        emb_dim2=10,
        l1_out_features=200,
        l2_out_features=27,
        num_epochs=1000,
        learning_rate=1e-1
        )

mlp_model.fit('train')

mlp_model.loss_function

# mlp_model.fit('train')
train_loss = mlp_model(Xtr, Ytr).item()
dev_loss = mlp_model(Xdev, Ydev).item()

print(f"Train loss: {train_loss:.4f}")
print(f"Dev loss: {dev_loss:.4f}")

test_loss=mlp_model(Xte, Yte).item()
print(test_loss)

mlp_model.generate_sampel(num_examples=100,itos=itos)

"""editing for good initializaiton and more productive learn
in hidden layer

---


"""

class MLPinit:
    def __init__(
        self,
        emb_dim1,
        emb_dim2,
        l1_out_features,
        l2_out_features,
        num_epochs,
        learning_rate,
        block_size=3,
        minibatch_size=32,
        loss_update_steps=1000,
        display_train_loss=True,
        seed=2147483647
        ):
          """Constructor for MLP class."""
          # Creating class attributes
          self.emb_dim_1 = emb_dim1
          self.emb_dim_2 = emb_dim2
          self.l1_out_features = l1_out_features
          self.l2_out_features = l2_out_features
          self.num_epochs = num_epochs
          self.learning_rate = learning_rate
          self.block_size = block_size
          self.minibatch_size = minibatch_size
          self.loss_update_steps = loss_update_steps
          self.display_train_loss = display_train_loss
          self.seed = seed

          g = torch.Generator().manual_seed(self.seed) # for reproducibility
          self.C = torch.randn((self.emb_dim_1,self.emb_dim_2), generator=g)
          self.W1=torch.randn((self.block_size*self.emb_dim_2,self.l1_out_features), generator=g)#*0.1
          # self.b1=torch.randn((self.l1_out_features), generator=g)#*0.01
          self.bngain = torch.ones((1, self.l1_out_features))
          self.bnbias = torch.zeros((1, self.l1_out_features))
          self.W2=torch.randn((self.l1_out_features,self.l2_out_features), generator=g)*0.01
          self.b2=torch.randn((self.l2_out_features), generator=g)*0.0
          self.parameters = [self.C, self.W1, self.b1, self.W2, self.b2]
          self.num_params = sum(p.nelement() for p in self.parameters)


          for p in self.parameters:
            p.requires_grad=True

    def __call__(self,x,y):
      #forward pass
      emb=self.C[x]
      self.hpreact=emb.view(-1,emb.shape[-1]*emb.shape[-2]) #hiddent preceptron activiation
      h= torch.tanh(self.hpreact@ self.W1+self.b1)
      self.h=h
      logits= h @ self.W2 + self.b2
      loss=F.cross_entropy(logits, y)
      return loss

    def fit(self,split):
      x,y={
      'train':(Xtr, Ytr),
       'test':(Xte, Yte),
       'dev':(Xdev, Ydev )
      }[split]
      loss_per_epoch = {}
      epoch_counter = notebook.tqdm(range(self.num_epochs))
      for k in epoch_counter:
          #mini batches
          xi=torch.randint(0,x.shape[0],(self.minibatch_size,))
          loss=self(x[xi],y[xi])
          if self.display_train_loss and ((k % self.loss_update_steps == 0) or (k == self.num_epochs-1)):
              epoch_counter.set_postfix({"train_loss": loss.item()})
          # Adding a loss computed to the history
          loss_per_epoch[f"epoch_{k+1}"] = loss.item()
          #backward pass
          for p in self.parameters:
            p.grad=None
          loss.backward()
          #update
          for p in self.parameters:
            p.data-=self.learning_rate*p.grad
      self.history = loss_per_epoch

mlp_model_init=MLPinit(
        emb_dim1=27,
        emb_dim2=10,
        l1_out_features=200,
        l2_out_features=27,
        num_epochs=1,
        learning_rate=1e-1
        )

mlp_model_init.fit('train')

plt.hist(mlp_model_init.hpreact.view(-1).item(), bins=50)
#prefer to be small values like(-3,3) to not produce much ones

mlp_model_init.hpreact

"""distribution of output of hidden layer"""

plt.hist(mlp_model_init.h.view(-1), bins=50)
#if it one (no learn because gradient will be 0 and will stop the effect of it down inputs)
#if it zero it will pass as it not exist because gradient will be(1*out.grad)

plt.figure(figsize=(20,10))
plt.imshow(h.aps()>0.99,cmap="gray",interpolation="nearest")
#if it is white that is mean that this neourn won't learn from this input
#if the whole column is white that deadneuron and that neuron never learned

"""random model accuracy"""

logits=0.6*torch.ones(27)
probs = torch.softmax(logits, dim=0)
loss=-probs[2].log()

mlp_model_init.history["epoch_1"], loss.item()

# Let's train a deeper network
# The classes we create here are the same API as nn.Module in PyTorch

class Linear:

  def __init__(self, fan_in, fan_out, bias=True):
    self.weight = torch.randn((fan_in, fan_out), generator=g) / fan_in**0.5
    self.bias = torch.zeros(fan_out) if bias else None

  def __call__(self, x):
    self.out = x @ self.weight
    if self.bias is not None:
      self.out += self.bias
    return self.out

  def parameters(self):
    return [self.weight] + ([] if self.bias is None else [self.bias])


class BatchNorm1d:

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.momentum = momentum
    self.training = True
    # parameters (trained with backprop)
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)
    # buffers (trained with a running 'momentum update')
    self.running_mean = torch.zeros(dim)
    self.running_var = torch.ones(dim)

  def __call__(self, x):
    # calculate the forward pass
    if self.training:
      xmean = x.mean(0, keepdim=True) # batch mean
      xvar = x.var(0, keepdim=True) # batch variance
    else:
      xmean = self.running_mean
      xvar = self.running_var
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    # update the buffers
    if self.training:
      with torch.no_grad():
        self.running_mean = (1 - self.momentum) * self.running_mean + self.momentum * xmean
        self.running_var = (1 - self.momentum) * self.running_var + self.momentum * xvar
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

class Tanh:
  def __call__(self, x):
    self.out = torch.tanh(x)
    return self.out
  def parameters(self):
    return []

n_embd = 10 # the dimensionality of the character embedding vectors
n_hidden = 100 # the number of neurons in the hidden layer of the MLP
g = torch.Generator().manual_seed(2147483647) # for reproducibility

C = torch.randn((vocab_size, n_embd),            generator=g)
layers = [
  Linear(n_embd * block_size, n_hidden, bias=False), BatchNorm1d(n_hidden), Tanh(),
  Linear(           n_hidden, n_hidden, bias=False), BatchNorm1d(n_hidden), Tanh(),
  Linear(           n_hidden, n_hidden, bias=False), BatchNorm1d(n_hidden), Tanh(),
  Linear(           n_hidden, n_hidden, bias=False), BatchNorm1d(n_hidden), Tanh(),
  Linear(           n_hidden, n_hidden, bias=False), BatchNorm1d(n_hidden), Tanh(),
  Linear(           n_hidden, vocab_size, bias=False), BatchNorm1d(vocab_size),
]
# layers = [
#   Linear(n_embd * block_size, n_hidden), Tanh(),
#   Linear(           n_hidden, n_hidden), Tanh(),
#   Linear(           n_hidden, n_hidden), Tanh(),
#   Linear(           n_hidden, n_hidden), Tanh(),
#   Linear(           n_hidden, n_hidden), Tanh(),
#   Linear(           n_hidden, vocab_size),
# ]

with torch.no_grad():
  # last layer: make less confident
  layers[-1].gamma *= 0.1
  #layers[-1].weight *= 0.1
  # all other layers: apply gain
  for layer in layers[:-1]:
    if isinstance(layer, Linear):
      layer.weight *= 1.0 #5/3

parameters = [C] + [p for layer in layers for p in layer.parameters()]
print(sum(p.nelement() for p in parameters)) # number of parameters in total
for p in parameters:
  p.requires_grad = True

# same optimization as last time
max_steps = 200000
batch_size = 32
lossi = []
ud = []

for i in range(max_steps):

  # minibatch construct
  ix = torch.randint(0, Xtr.shape[0], (batch_size,), generator=g)
  Xb, Yb = Xtr[ix], Ytr[ix] # batch X,Y

  # forward pass
  emb = C[Xb] # embed the characters into vectors
  x = emb.view(emb.shape[0], -1) # concatenate the vectors
  for layer in layers:
    x = layer(x)
  loss = F.cross_entropy(x, Yb) # loss function

  # backward pass
  for layer in layers:
    layer.out.retain_grad() # AFTER_DEBUG: would take out retain_graph
  for p in parameters:
    p.grad = None
  loss.backward()

  # update
  lr = 0.1 if i < 150000 else 0.01 # step learning rate decay
  for p in parameters:
    p.data += -lr * p.grad

  # track stats
  if i % 10000 == 0: # print every once in a while
    print(f'{i:7d}/{max_steps:7d}: {loss.item():.4f}')
  lossi.append(loss.log10().item())
  with torch.no_grad():
    ud.append([((lr*p.grad).std() / p.data.std()).log10().item() for p in parameters])

  if i >= 1000:
    break # AFTER_DEBUG: would take out obviously to run full optimization

# visualize histograms
plt.figure(figsize=(20, 4)) # width and height of the plot
legends = []
for i, layer in enumerate(layers[:-1]): # note: exclude the output layer
  if isinstance(layer, Tanh):
    t = layer.out
    print('layer %d (%10s): mean %+.2f, std %.2f, saturated: %.2f%%' % (i, layer.__class__.__name__, t.mean(), t.std(), (t.abs() > 0.97).float().mean()*100))
    hy, hx = torch.histogram(t, density=True)
    plt.plot(hx[:-1].detach(), hy.detach())
    legends.append(f'layer {i} ({layer.__class__.__name__}')
plt.legend(legends);
plt.title('activation distribution')

# visualize histograms
plt.figure(figsize=(20, 4)) # width and height of the plot
legends = []
for i, layer in enumerate(layers[:-1]): # note: exclude the output layer
  if isinstance(layer, Tanh):
    t = layer.out.grad
    print('layer %d (%10s): mean %+f, std %e' % (i, layer.__class__.__name__, t.mean(), t.std()))
    hy, hx = torch.histogram(t, density=True)
    plt.plot(hx[:-1].detach(), hy.detach())
    legends.append(f'layer {i} ({layer.__class__.__name__}')
plt.legend(legends);
plt.title('gradient distribution')

# visualize histograms
plt.figure(figsize=(20, 4)) # width and height of the plot
legends = []
for i,p in enumerate(parameters):
  t = p.grad
  if p.ndim == 2:
    print('weight %10s | mean %+f | std %e | grad:data ratio %e' % (tuple(p.shape), t.mean(), t.std(), t.std() / p.std()))
    hy, hx = torch.histogram(t, density=True)
    plt.plot(hx[:-1].detach(), hy.detach())
    legends.append(f'{i} {tuple(p.shape)}')
plt.legend(legends)
plt.title('weights gradient distribution');

plt.figure(figsize=(20, 4))
legends = []
for i,p in enumerate(parameters):
  if p.ndim == 2:
    plt.plot([ud[j][i] for j in range(len(ud))])
    legends.append('param %d' % i)
plt.plot([0, len(ud)], [-3, -3], 'k') # these ratios should be ~1e-3, indicate on plot
plt.legend(legends);

@torch.no_grad() # this decorator disables gradient tracking
def split_loss(split):
  x,y = {
    'train': (Xtr, Ytr),
    'val': (Xdev, Ydev),
    'test': (Xte, Yte),
  }[split]
  emb = C[x] # (N, block_size, n_embd)
  x = emb.view(emb.shape[0], -1) # concat into (N, block_size * n_embd)
  for layer in layers:
    x = layer(x)
  loss = F.cross_entropy(x, y)
  print(split, loss.item())

# put layers into eval mode
for layer in layers:
  layer.training = False
split_loss('train')
split_loss('val')

# sample from the model
g = torch.Generator().manual_seed(2147483647 + 10)

for _ in range(20):

    out = []
    context = [0] * block_size # initialize with all ...
    while True:
      # forward pass the neural net
      emb = C[torch.tensor([context])] # (1,block_size,n_embd)
      x = emb.view(emb.shape[0], -1) # concatenate the vectors
      for layer in layers:
        x = layer(x)
      logits = x
      probs = F.softmax(logits, dim=1)
      # sample from the distribution
      ix = torch.multinomial(probs, num_samples=1, generator=g).item()
      # shift the context window and track the samples
      context = context[1:] + [ix]
      out.append(ix)
      # if we sample the special '.' token, break
      if ix == 0:
        break

    print(''.join(itos[i] for i in out)) # decode and print the generated word