# -*- coding: utf-8 -*-
"""trigrad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ra2PidfXIRSGVp0-JXQMkqmQ3Oz8O5a1
"""

import math
words = open('names.txt', 'r').read().splitlines()
l=len(words)
train=words[:math.floor(0.8*l)]
dev=words[math.floor(0.8*l):math.floor(0.9*l)]
test=words[math.floor(0.9*l):]
import torch

print(len(train)/len(words))
print(len(dev)/len(words))
print(len(test)/len(words))

chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

N = torch.zeros((27,27, 27), dtype=torch.int32)
for w in words:
# for w in words[:1]:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2,ch3 in zip(chs, chs[1:],chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    N[ix1,ix2, ix3] += 1

P = (N+1).float()
P /= P.sum(2, keepdims=True)
g=torch.Generator().manual_seed(2147483647)
for i in range(5):
  out=['.','.']
  while(True):
    p=P[stoi[out[-2]],stoi[out[-1]]]
    iy=torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
    out.append(itos[iy])
    if iy==0:
      break
  print(''.join(out[2:]))

log_liklihood=0.0
n=0
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1,ch2,ch3 in zip(chs,chs[1:],chs[2:]):
    l=P[stoi[ch1],stoi[ch2],stoi[ch3]]
    log_liklihood+=torch.log(l)
    n+=1
nll=-log_liklihood
print(nll/n)

"""**Tigrad nn**"""

xs=[]
ys=[]
for w in train:
  chs = ['.'] + list(w) + ['.']
  for ch1,ch2,ch3 in zip(chs,chs[1:],chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    xs.append((ix1,ix2))
    ys.append(ix3)
xs=torch.tensor(xs)
ys=torch.tensor(ys)
# print(xs)
print(ys.shape)

import torch.nn.functional as f
xenc=f.one_hot(xs,num_classes=27).float()
xenc.shape

g=torch.Generator().manual_seed(2147483647)
W=torch.randn((27*2,27),generator=g,requires_grad=True)
for k in range(1000):
  logit=xenc.view(-1,27*2) @ W
  counts=logit.exp()
  probs=counts/counts.sum(1,keepdim=True)
  loss=-probs[torch.arange(ys.shape[0]),ys].log().mean()+0.01*(W**2).mean()
  W.grad = None
  loss.backward()
  W.data += -3 * W.grad
print(loss.item())

"""using f_cross_entropy"""

xenc = f.one_hot(xs, num_classes=27).float()
logits = xenc.view(-1, 27*2) @ W

counts = logits.exp()
probs = counts / counts.sum(1, keepdims=True)
loss = -probs[torch.arange(ys.shape[0]), ys].log().mean() + 0.01*(W**2).mean()

loss, f.cross_entropy(logits, ys) + 0.01*(W**2).mean()

"""**evaluation on test and dev set**"""

loss=[]
for w in test:
  chs = ['.'] + list(w) + ['.']
  for ch1,ch2,ch3 in zip(chs,chs[1:],chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    xenc = f.one_hot(torch.tensor((ix1, ix2)), num_classes=27).float()
    logit=xenc.view(-1,27*2) @ W.data
    counts=logit.exp()
    probs=counts/counts.sum(1,keepdim=True)
    loss.append(-probs[0,ix3].log())
loss=torch.tensor(loss).mean()
print(loss.item())

loss=[]
for w in dev:
  chs = ['.'] + list(w) + ['.']
  for ch1,ch2,ch3 in zip(chs,chs[1:],chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    xenc = f.one_hot(torch.tensor((ix1, ix2)), num_classes=27).float()
    logit=xenc.view(-1,27*2) @ W
    counts=logit.exp()
    probs=counts/counts.sum(1,keepdim=True)
    loss.append(-probs[0,ix3].log())
loss=torch.tensor(loss).mean()

g=torch.Generator().manual_seed(2147483647)
for i in range(20):
  ix=0
  out=[]
  while(True):
    # logit=w[ix]
    xenc=f.one_hot(torch.tensor([ix]),num_classes=54).float()
    logit=xenc @ w
    counts=logit.exp()
    p=counts/counts.sum(1,keepdim=True)
    ix=torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
    out.append(itos[ix])
    if ix==0:
      break
  print(''.join(out))