# -*- coding: utf-8 -*-
"""Bulding GPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zsi2Bp2wCFP_6vvgQX6or7sSnZg0y6mJ
"""

import torch
import torch.nn as nn
from torch.nn import functional as F
from tqdm.notebook import tqdm
import urllib.request

#hyperprameter
batch_size=64
block_size=256
max_iters=5000
lr=3e-4
device='cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
eval_interval = 500
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
torch.manual_seed(1337)

url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
urllib.request.urlretrieve(url, "input.txt")

with open('input.txt', 'r', encoding='utf-8') as f:
  text = f.read()

chars=sorted(list(set(text)))
vocab_size=len(chars)
print(' '.join(chars))
print(vocab_size)

stoi={ch:i for i,ch in enumerate(chars)}
itos={i:ch for i,ch in enumerate(chars)}
encode=lambda s:[stoi[c] for c in s]
decode=lambda l:''.join([itos[i] for i in l])


data=torch.tensor(encode(text),dtype=torch.long)
print(data.shape, data.dtype)

#train and test split
n=int(0.9*len(data))
train_data=data[:n]
val_data = data[n:]

#data load
def get_batch(split):
  data=train_data if split=="train" else val_data
  ix=torch.randint(len(data)-block_size,(batch_size,))
  x=torch.stack([data[i:i+block_size]for i in ix])
  y=torch.stack([data[i+1:i+block_size+1]for i in ix])
  x,y=x.to(device),y.to(device)
  return x,y

@torch.no_grad()
def estimate_loss():
  out={}
  model.eval()
  for split in ['train','val']:
    losses=torch.zeros(eval_iters)
    for k in range(eval_iters):
      X,Y=get_batch(split)
      logits,loss=model(X,Y)
      losses[k]=loss.item()
    out[split]=losses.mean()
  model.train()
  return out

class Head(nn.Module):
  def __init__(self,head_size):
    super().__init__()
    self.key=nn.Linear(n_embd,head_size,bias=False)
    self.query=nn.Linear(n_embd,head_size,bias=False)
    self.value=nn.Linear(n_embd,head_size,bias=False)
    self.register_buffer('tril',torch.tril(torch.ones(block_size,block_size)))
    self.dropout=nn.Dropout(dropout)
    
  def forward(self,x):
    B,T,C=x.shape
    k=self.key(x)
    q=self.query(x)
    v=self.value(x)
    wei=q @ k.transpose(-2,-1) * C**-0.5
    wei=wei.masked_fill(self.tril[:T,:T]==0,float('-inf'))
    wei=F.softmax(wei,dim=-1)
    wei=self.dropout(wei)
    out=wei @ v
    return out

class multi_head_attention(nn.Module):
  def __init__(self,num_heads,head_size):
    super().__init__()
    self.heads=nn.ModuleList([Head(head_size) for _ in range(num_heads)])
    self.proj=nn.Linear(n_embd,n_embd)
    self.dropout=nn.Dropout(dropout)
  def forward(self,x):
    out=torch.cat([h(x) for h in self.heads],dim=-1)
    out=self.dropout(self.proj(out))
    return out

class feed_forward(nn.Module):
  def __init__(self,n_embd):
    super().__init__()
    self.net=nn.Sequential(
        nn.Linear(n_embd,n_head*n_embd),
        nn.ReLU(),
        nn.Linear(n_head*n_embd,n_embd),
        nn.Dropout(dropout)
    )
  def forward(self,x):
    return self.net(x) 

class block(nn.Module):
  def __init__(self,n_embd,n_head):
    super().__init__()
    head_size=n_embd//n_head
    self.sa_head=multi_head_attention(n_head,head_size)
    self.ffwd=feed_forward(n_embd)
    self.l1=nn.LayerNorm(n_embd) #B,T acts like B it is out normalization for each token depend only on feature of this token (C level)
    self.l2=nn.LayerNorm(n_embd)
  def forward(self,x):
    #norm -->multihead attention -->norm-->feedforward    and there is residual 
    x=x+self.sa_head(self.l1(x)) #residual connection 
    x=x+self.ffwd(self.l2(x))
    return x
  
class BigramLanguageModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.token_embedding_table=nn.Embedding(vocab_size,n_embd)
    self.position_embedding_table=nn.Embedding(block_size,n_embd)
    # self.sa_head=single_head_attention(n_embd)
    # self.sa_head=multi_head_attention(4,n_embd//4)
    # self.ffwd=feed_forward(n_embd)
    self.blocks=block(n_embd,n_head)
    self.lm_head=nn.Linear(n_embd,vocab_size)

  def forward(self,idx,target=None):
    tok_emb=self.token_embedding_table(idx)
    pos_emb=self.position_embedding_table(torch.arange(T,device=device)) #(T,C)
    x=tok_emb+pos_emb
    # x=self.sa_head(x)
    # x=self.ffwd(x)
    x=self.blocks(x)
    logits=self.lm_head(x)
    if target is None:
      loss=None
    else:
     B,T,C=logits.shape
     logits=logits.view(B*T,C)
     target=target.view(B*T)
     loss=F.cross_entropy(logits,target)
    return logits,loss

  def generate(self,idx,max_new_tokens):
    for _ in range(max_new_tokens):
      idx_cond=idx[:,-block_size:]
      logits,loss=self(idx_cond)
      logits=logits[:,-1,:]
      probs=F.softmax(logits,dim=-1)
      idx_next=torch.multinomial(probs,num_samples=1)
      idx=torch.cat((idx,idx_next),dim=1)
    return idx

model=BigramLanguageModel()
m=model.to(device)

#create pytorch optimizer
optimizer=torch.optim.AdamW(model.parameters(),lr)

for iter in tqdm(range(max_iters)):
  if iter%eval_interval==0 or iter==max_iters-1:
    losses=estimate_loss()
    print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")
    #sample a batch of data
  xb,yb=get_batch("train")
  #evaluate the loss
  logits,loss=model(xb,yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()
  #generate from the model
with open('output.txt','w',encoding='utf-8') as f:
  f.write(decode(m.generate(idx=torch.zeros((1,1), dtype=torch.long,device=device),max_new_tokens=10000)[0].tolist()))
